### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by jose31canizar** [maar9185/Arendall_CSCI2270_FinalProject#2]
I'm unable to compile the game since it includes JSON and I have a mac. Is the JSON library necessary? Thanks.

**Comment by maar9185** [comment]
Hey Jose,

I just had the JSON library there from a previous assignment. I updated it
where there is no dependence on JSON anymore. If you can re-clone my
repository and grade it again I would really appreciate it!

Thank you,

Matt

On Sat, May 2, 2015 at 9:12 AM, jose31canizar notifications@github.com
wrote:

> I'm unable to compile the game since it includes JSON and I have a mac. Is
> the JSON library necessary? Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maar9185/Arendall_CSCI2270_FinalProject/issues/2.

## 

Matthew Arendall
Undergraduate Research Assistant
Antenna Research Group
Department of Electrical Engineering
University of Colorado Boulder

**Comment by jose31canizar** [comment]
Cool, that fixed it.
